---

- name: Подключение репозитория docker
  include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Удаление предыдущей версии docker
  include_tasks: uninstall.yml

- name: Установка '{{ docker_package_version }}'
  include_tasks: install-specific-version.yml

- name: Write settings to /etc/docker/daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0644
    owner: root
  register: template_result

- name: Restart docker service
  systemd:
    name: docker
    state: restarted
  when: template_result.changed

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- include_tasks: docker-users.yml
  when: docker_users | length > 0
