---

# Docker apt packeg version
docker_package_version: ""

# Docker Compose options.
docker_install_compose: false
docker_compose_version: "1.29.2"
docker_compose_path: /usr/local/bin/docker-compose

# Used only for Debian/Ubuntu. Switch 'stable' to 'nightly' if needed.
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_ignore_key_error: true
docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

# A list of users who will be added to the docker group.
docker_users: []

# Configure docker daemon
docker_daemon_default_address_pools_base: "10.124.0.0/22"
docker_daemon_default_address_pools_size: "26"
docker_daemon_data_root: ""
docker_daemon_storage_driver: "overlay2"
